show_link = [ "application", "abc", "abc", "abc",]
[[upstreams]]
type = "direct"
enabled = true
weight = 10

[general]
prefer_ipv6 = false
fast_mode = true
use_middle_proxy = false

[server]
port = 443
listen_addr_ipv4 = "0.0.0.0"
listen_addr_ipv6 = "::"

[censorship]
tls_domain = "petrovich.ru"
mask = true
mask_port = 443
fake_cert_len = 2048

[general.modes]
classic = false
secure = false
tls = true

[access.users]
application = "f7500d69d0479eb1c90454490aa7096d"
abc = "f57b4744b742f49a33f847dffde500e9"

[access.user_max_tcp_conns]
application = 0
abc = 50

[access.user_max_unique_ips]
application = 0
abc = 2
